server.port=${SERVER_PORT}

services.auth.url=http://${AUTH_SERVICE_HOST}:${AUTH_SERVICE_PORT}

services.user.url=http://${USER_SERVICE_HOST}:${USER_SERVICE_PORT}

services.order.url=http://${ORDER_SERVICE_HOST}:${ORDER_SERVICE_PORT}

services.payment.url=http://${PAYMENT_SERVICE_HOST}:${PAYMENT_SERVICE_PORT}