spring.application.name=api-gateway

spring.config.import=optional:file:.env[.properties]

spring.profiles.active=${ACTIVE_PROFILE}

server.port=${SERVER_PORT}

internal.api-key=${INTERNAL_API_KEY}

spring.cloud.gateway.server.webflux.routes[0].id=auth-api-docs
spring.cloud.gateway.server.webflux.routes[0].uri=${services.auth.url}
spring.cloud.gateway.server.webflux.routes[0].predicates=Path=/auth-service/api-docs
spring.cloud.gateway.server.webflux.routes[0].filters=SetPath=/api-docs

spring.cloud.gateway.server.webflux.routes[1].id=user-api-docs
spring.cloud.gateway.server.webflux.routes[1].uri=${services.user.url}
spring.cloud.gateway.server.webflux.routes[1].predicates=Path=/user-service/api-docs
spring.cloud.gateway.server.webflux.routes[1].filters=SetPath=/api-docs

spring.cloud.gateway.server.webflux.routes[2].id=order-api-docs
spring.cloud.gateway.server.webflux.routes[2].uri=${services.order.url}
spring.cloud.gateway.server.webflux.routes[2].predicates=Path=/order-service/api-docs
spring.cloud.gateway.server.webflux.routes[2].filters=SetPath=/api-docs

spring.cloud.gateway.server.webflux.routes[3].id=auth-service-internal
spring.cloud.gateway.server.webflux.routes[3].uri=${services.auth.url}
spring.cloud.gateway.server.webflux.routes[3].predicates=Path=/internal/auth/**
spring.cloud.gateway.server.webflux.routes[3].filters[0].name=InternalApiKeyFilter

spring.cloud.gateway.server.webflux.routes[4].id=auth-service
spring.cloud.gateway.server.webflux.routes[4].uri=${services.auth.url}
spring.cloud.gateway.server.webflux.routes[4].predicates=Path=/api/auth/**

spring.cloud.gateway.server.webflux.routes[5].id=user-service-internal
spring.cloud.gateway.server.webflux.routes[5].uri=${services.user.url}
spring.cloud.gateway.server.webflux.routes[5].predicates=Path=/internal/users/**
spring.cloud.gateway.server.webflux.routes[5].filters[0].name=InternalApiKeyFilter

spring.cloud.gateway.server.webflux.routes[6].id=user-service-users
spring.cloud.gateway.server.webflux.routes[6].uri=${services.user.url}
spring.cloud.gateway.server.webflux.routes[6].predicates=Path=/api/users/**

spring.cloud.gateway.server.webflux.routes[7].id=user-service-payment-cards
spring.cloud.gateway.server.webflux.routes[7].uri=${services.user.url}
spring.cloud.gateway.server.webflux.routes[7].predicates=Path=/api/payment-cards/**

spring.cloud.gateway.server.webflux.routes[8].id=user-service-user-payment-cards
spring.cloud.gateway.server.webflux.routes[8].uri=${services.user.url}
spring.cloud.gateway.server.webflux.routes[8].predicates=Path=/api/users/*/payment-cards/**

spring.cloud.gateway.server.webflux.routes[9].id=order-service-orders
spring.cloud.gateway.server.webflux.routes[9].uri=${services.order.url}
spring.cloud.gateway.server.webflux.routes[9].predicates=Path=/api/orders/**

spring.cloud.gateway.server.webflux.routes[10].id=order-service-items
spring.cloud.gateway.server.webflux.routes[10].uri=${services.order.url}
spring.cloud.gateway.server.webflux.routes[10].predicates=Path=/api/items/**

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui

springdoc.swagger-ui.urls[0].name=API Gateway
springdoc.swagger-ui.urls[0].url=/api-docs

springdoc.swagger-ui.urls[1].name=Auth Service
springdoc.swagger-ui.urls[1].url=/auth-service/api-docs

springdoc.swagger-ui.urls[2].name=User Service
springdoc.swagger-ui.urls[2].url=/user-service/api-docs

springdoc.swagger-ui.urls[3].name=Order Service
springdoc.swagger-ui.urls[3].url=/order-service/api-docs