server.port=${SERVER_PORT}

services.auth.url=${AUTH_SERVICE_DOCKER_URL}

services.user.url=${USER_SERVICE_DOCKER_URL}

services.order.url=${ORDER_SERVICE_DOCKER_URL}

services.payment.url=${PAYMENT_SERVICE_DOCKER_URL}